#!/usr/bin/env python3
# Copyright 2012 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at <http://aws.amazon.com/apache2.0/>
# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
'''TODO.'''
from functools import update_wrapper
import sys
import awscli.clidriver
import botocore.endpoint
from botocore.endpoint import BotocoreHTTPSession
from harlib.objects import HarFile

BOTOCOREHTTPSESSION_SEND = BotocoreHTTPSession.send
FILENAME = 'out.har'
ENTRIES = []


def har_send(self, request, **kwargs):
    '''TODO.'''
    response = BOTOCOREHTTPSESSION_SEND(self, request, **kwargs)
    response.request = request.original
    ENTRIES.append(response)
    return response


def har_patch():
    '''TODO.'''
    botocore.endpoint.BotocoreHTTPSession.send = \
        update_wrapper(har_send, BOTOCOREHTTPSESSION_SEND)


def har_dump():
    '''TODO.'''
    har_file = HarFile(ENTRIES)
    print(har_file.dumps())


def main():
    '''TODO.'''
    har_patch()
    status = awscli.clidriver.main()
    har_dump()
    return status


if __name__ == '__main__':
    sys.exit(main())
