#!/usr/bin/env python3
# Copyright 2012 Amazon.com, Inc. or its affiliates. All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License"). You
# may not use this file except in compliance with the License. A copy of
# the License is located at

#     http://aws.amazon.com/apache2.0/

# or in the "license" file accompanying this file. This file is
# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
# ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
import sys
import awscli.clidriver
import botocore.endpoint
from botocore.endpoint import BotocoreHTTPSession
from harlib.objects import HarFile
from functools import update_wrapper

_BotocoreHTTPSession = BotocoreHTTPSession
_BotocoreHTTPSession_init = BotocoreHTTPSession.__init__
_BotocoreHTTPSession_send = BotocoreHTTPSession.send
_default_filename = 'out.har'
_entries = []


def harlib_init(self, filename=None):
    self._entries = []
    self._filename = str(filename) if filename else ''
    self._kept_sockopts = []
    self.keep_entries = True
    self.keep_content = True
    self.keep_client_options = False
    self.keep_server_options = False
    self.keep_socket_options = False


def har_send(self, request, **kwargs):
    response = _BotocoreHTTPSession_send(self, request, **kwargs)
    response.request = request.original
    _entries.append(response)
    return response


def har_patch():
    botocore.endpoint.BotocoreHTTPSession.send = \
        update_wrapper(har_send, _BotocoreHTTPSession_send)


def har_dump():
    har_file = HarFile(_entries)
    print(har_file.dumps())


def main():
    har_patch()

    status = awscli.clidriver.main()

    har_dump()

    return status


if __name__ == '__main__':
    sys.exit(main())
